// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// acc_sum_n_idx1K
void acc_sum_n_idx1K(IntegerVector idx, NumericVector v, NumericVector sumv, IntegerVector n);
RcppExport SEXP _StreamCatR_acc_sum_n_idx1K(SEXP idxSEXP, SEXP vSEXP, SEXP sumvSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumv(sumvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    acc_sum_n_idx1K(idx, v, sumv, n);
    return R_NilValue;
END_RCPP
}
// acc_sum_n_map_centers1K
void acc_sum_n_map_centers1K(IntegerVector idx, const double xminZ, const double ymaxZ, const double rxZ, const double ryZ, const int nx, const int ny, NumericVector valsP, const double xminP, const double ymaxP, const double rxP, const double ryP, const int ncP, const int nrP, NumericVector sumv, IntegerVector n);
RcppExport SEXP _StreamCatR_acc_sum_n_map_centers1K(SEXP idxSEXP, SEXP xminZSEXP, SEXP ymaxZSEXP, SEXP rxZSEXP, SEXP ryZSEXP, SEXP nxSEXP, SEXP nySEXP, SEXP valsPSEXP, SEXP xminPSEXP, SEXP ymaxPSEXP, SEXP rxPSEXP, SEXP ryPSEXP, SEXP ncPSEXP, SEXP nrPSEXP, SEXP sumvSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< const double >::type xminZ(xminZSEXP);
    Rcpp::traits::input_parameter< const double >::type ymaxZ(ymaxZSEXP);
    Rcpp::traits::input_parameter< const double >::type rxZ(rxZSEXP);
    Rcpp::traits::input_parameter< const double >::type ryZ(ryZSEXP);
    Rcpp::traits::input_parameter< const int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< const int >::type ny(nySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type valsP(valsPSEXP);
    Rcpp::traits::input_parameter< const double >::type xminP(xminPSEXP);
    Rcpp::traits::input_parameter< const double >::type ymaxP(ymaxPSEXP);
    Rcpp::traits::input_parameter< const double >::type rxP(rxPSEXP);
    Rcpp::traits::input_parameter< const double >::type ryP(ryPSEXP);
    Rcpp::traits::input_parameter< const int >::type ncP(ncPSEXP);
    Rcpp::traits::input_parameter< const int >::type nrP(nrPSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumv(sumvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    acc_sum_n_map_centers1K(idx, xminZ, ymaxZ, rxZ, ryZ, nx, ny, valsP, xminP, ymaxP, rxP, ryP, ncP, nrP, sumv, n);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StreamCatR_acc_sum_n_idx1K", (DL_FUNC) &_StreamCatR_acc_sum_n_idx1K, 4},
    {"_StreamCatR_acc_sum_n_map_centers1K", (DL_FUNC) &_StreamCatR_acc_sum_n_map_centers1K, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_StreamCatR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
